#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ENV_FILE:-$ROOT/.env}"

drop_env() {
  local key="$1" tmp
  [ -f "$ENV_FILE" ] || return 0
  tmp="$(mktemp)"
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  mv "$tmp" "$ENV_FILE"
  printf '  %s✓ removed%s %s from %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

find_developer_id() {
  security find-identity -v -p codesigning 2>/dev/null \
    | sed -n 's/.*"\(Developer ID Application: [^"]*\)".*/\1/p' | head -1
}

team_id_from_cert() {
  security find-certificate -c "Developer ID Application" -p 2>/dev/null \
    | openssl x509 -noout -subject 2>/dev/null \
    | sed -n 's/.*OU *= *\([A-Z0-9]\{10\}\).*/\1/p' | head -1
}

banner "DroidBerth · Developer ID + notarization setup"

# ── Stage 1: current state ────────────────────────────────────────────────
stage "Current state"
say "Reading what this machine already has, so we only do the missing parts."
printf '\n'
say "codesigning identities:"
security find-identity -v -p codesigning 2>/dev/null | sed 's/^/    /' || true
printf '\n'
EXISTING_DID="$(find_developer_id || true)"
if [[ -n "$EXISTING_DID" ]]; then
  printf '  %s✓ Developer ID already installed%s\n' "$GREEN" "$RESET"
  note "  $EXISTING_DID"
else
  printf '  %s✗ no Developer ID Application certificate%s\n' "$YELLOW" "$RESET"
fi
say "notarytool keychain profiles:"
if xcrun notarytool history 2>&1 | grep -qi 'must provide credentials'; then
  note "  none usable yet (no profile and no env credentials)"
else
  xcrun notarytool history 2>&1 | head -3 | sed 's/^/    /' || true
fi
printf '\n'
say "connected android devices:"
"$ROOT/vendor/platform-tools/adb" devices -l 2>/dev/null | sed 's/^/    /' || note "  adb not installed yet"
printf '\n'
pause "Press Enter to continue"
# ──────────────────────────────────────────────────────────────────────────

# ── Stage 2: Apple Developer Program membership ───────────────────────────
stage "Apple Developer Program membership"
say "Developer ID certificates only exist for paid Apple Developer Program members."
say "Cost: 99 USD/year (individual) — organization accounts additionally need a D-U-N-S number."
printf '\n'
open_url "https://developer.apple.com/account"
step "Sign in and look for 'Membership details' in the left sidebar."
step "If it shows a Team ID and 'Active', you are enrolled — skip to Stage 3."
step "If not, click 'Enroll' and finish the purchase flow, then come back."
printf '\n'
warn "Enrollment approval can take from minutes to a couple of days."
note "Come back and re-run this wizard when it says Active; it remembers what is done."
printf '\n'
pause "Press Enter once your membership shows Active"
# ──────────────────────────────────────────────────────────────────────────

# ── Stage 3: create the Developer ID Application certificate ──────────────
stage "Create a Developer ID Application certificate"
say "Use Xcode. It creates the key, uploads the CSR, downloads the cert and"
say "installs it into your login keychain in one go — no manual CSR dance."
printf '\n'
step "Open Xcode → Settings (Cmd-,) → Accounts."
step "Select your Apple ID, then click 'Manage Certificates...'."
step "Click the '+' at the bottom-left and choose 'Developer ID Application'."
step "Wait for the row to appear, then click 'Done'."
printf '\n'
note "Manual alternative if Xcode will not do it: developer.apple.com → Certificates,"
note "Identifiers & Profiles → Certificates → + → Developer ID Application, upload a CSR"
note "from Keychain Access → Certificate Assistant → Request a Certificate From a"
note "Certificate Authority, then double-click the downloaded .cer to install it."
printf '\n'
open_url "https://developer.apple.com/account/resources/certificates/list"
pause "Press Enter once the certificate exists"
# ──────────────────────────────────────────────────────────────────────────

# ── Stage 4: verify the certificate and capture Team ID ───────────────────
stage "Verify the certificate and capture the Team ID"
say "Checking the login keychain for a usable Developer ID identity."
printf '\n'
IDENTITY="$(find_developer_id || true)"
if [[ -z "$IDENTITY" ]]; then
  warn "No 'Developer ID Application' identity found in the keychain."
  note "Check Keychain Access → login → My Certificates: the row must have a"
  note "disclosure triangle (a private key attached). A cert without its private"
  note "key cannot sign anything and will not show up here."
  printf '\n'
  pause "Fix that, then press Enter to re-check"
  IDENTITY="$(find_developer_id || true)"
fi
if [[ -z "$IDENTITY" ]]; then
  warn "Still nothing. Paste the identity manually if you know it."
  ask APPLE_SIGNING_IDENTITY "Identity string (e.g. Developer ID Application: Name (TEAMID)):"
else
  printf '  %s✓ found%s %s\n' "$GREEN" "$RESET" "$IDENTITY"
  APPLE_SIGNING_IDENTITY="$IDENTITY"
fi
printf '\n'
DETECTED_TEAM="$(team_id_from_cert || true)"
if [[ -n "$DETECTED_TEAM" ]]; then
  note "Team ID read from the certificate: $DETECTED_TEAM"
  APPLE_TEAM_ID="$DETECTED_TEAM"
else
  note "Could not read the Team ID from the certificate; get it from the portal."
  open_url "https://developer.apple.com/account"
  step "Membership details → copy the 10-character Team ID."
  ask APPLE_TEAM_ID "Paste the Team ID:"
fi
printf '\n'
note "Signing identity : $APPLE_SIGNING_IDENTITY"
note "Team ID          : $APPLE_TEAM_ID"
write_env APPLE_SIGNING_IDENTITY "$APPLE_SIGNING_IDENTITY"
write_env APPLE_TEAM_ID "$APPLE_TEAM_ID"
pause "Press Enter to continue"
# ──────────────────────────────────────────────────────────────────────────

# ── Stage 5: app-specific password ────────────────────────────────────────
stage "Create an app-specific password"
say "notarytool authenticates with an app-specific password, not your Apple ID"
say "password. Apple issues it once — copy it now, it is never shown again."
printf '\n'
open_url "https://account.apple.com"
step "Sign in, then go to 'Sign-In and Security' → 'App-Specific Passwords'."
step "Click the '+' (or 'Generate an App-Specific Password')."
step "Name it something recognisable, e.g. 'droidberth-notarytool'."
step "Copy the generated password — it looks like abcd-efgh-ijkl-mnop."
printf '\n'
ask APPLE_ID "Your Apple ID (email):"
ask_secret APPLE_PASSWORD "Paste the app-specific password:"
write_env APPLE_ID "$APPLE_ID"
write_env APPLE_PASSWORD "$APPLE_PASSWORD"
pause "Press Enter to continue"
# ──────────────────────────────────────────────────────────────────────────

# ── Stage 6: store and verify notarytool credentials ──────────────────────
stage "Store and verify notarytool credentials"
say "Saving the credentials into the login keychain as a reusable profile, so"
say "scripts/notarize.sh never needs the password on its command line."
printf '\n'
PROFILE="${NOTARY_PROFILE:-droidberth}"
case "$APPLE_PASSWORD" in
  *-*-*-*) note "password shape looks right (abcd-efgh-ijkl-mnop)" ;;
  *)
    warn "that does not look like an app-specific password"
    note "expected abcd-efgh-ijkl-mnop; an Apple ID password or a 2FA code will not work"
    printf '\n'
    ;;
esac
STORED=0
if xcrun notarytool store-credentials "$PROFILE" \
     --apple-id "$APPLE_ID" \
     --team-id "$APPLE_TEAM_ID" \
     --password "$APPLE_PASSWORD" >/dev/null 2>&1; then
  printf '  %s✓ stored%s keychain profile "%s"\n' "$GREEN" "$RESET" "$PROFILE"
  STORED=1
else
  warn "store-credentials failed — re-check the app-specific password and Team ID."
fi
printf '\n'
say "Verifying the profile actually authenticates against Apple:"
if [ "$STORED" = "1" ] && xcrun notarytool history --keychain-profile "$PROFILE" >/dev/null 2>&1; then
  printf '  %s✓ notarytool authenticated%s\n' "$GREEN" "$RESET"
  xcrun notarytool history --keychain-profile "$PROFILE" 2>&1 | head -4 | sed 's/^/    /'
  write_env NOTARY_PROFILE "$PROFILE"
else
  warn "notarytool did NOT authenticate, so no profile was recorded."
  drop_env NOTARY_PROFILE
  note "scripts/notarize.sh will fall back to the APPLE_ID/APPLE_PASSWORD values in .env."
  SKIPPED+=("notarytool credentials — re-run this wizard and paste a real app-specific password")
fi
printf '\n'
pause "Press Enter to continue"
# ──────────────────────────────────────────────────────────────────────────

# ── Stage 7: lock down .env ───────────────────────────────────────────────
stage "Lock down the credentials file"
say "The app-specific password now lives in $ENV_FILE. Keep it out of git and"
say "readable only by you."
printf '\n'
if grep -qx '.env' "$ROOT/.gitignore" 2>/dev/null; then
  printf '  %s✓ .env is already gitignored%s\n' "$GREEN" "$RESET"
else
  printf '\n.env\n' >> "$ROOT/.gitignore"
  printf '  %s✓ added .env to .gitignore%s\n' "$GREEN" "$RESET"
fi
chmod 600 "$ENV_FILE" 2>/dev/null || true
note "  chmod 600 $ENV_FILE"
printf '\n'
say "scripts/env.sh sources this file automatically, so build.sh, resign.sh and"
say "notarize.sh all pick the values up without you exporting anything."
printf '\n'
pause "Press Enter to continue"
# ──────────────────────────────────────────────────────────────────────────

# ── Stage 8: device-side USB debugging ────────────────────────────────────
stage "Android device: enable USB debugging"
say "Separate prerequisite, same spirit. The phone is on the USB bus but exposes"
say "no interfaces, which means it is in charge-only mode."
printf '\n'
step "On the phone: Settings → About phone → tap 'Build number' 7 times."
step "Then Settings → System & updates → Developer options → enable 'USB debugging'."
step "Pull down the notification shade, tap the USB notification, choose 'Transfer files'."
step "Accept the 'Allow USB debugging?' prompt on the phone."
printf '\n'
warn "Huawei/EMUI note: 'Allow ADB debugging in charge only mode' is a separate"
warn "toggle in Developer options — it is off by default and easy to miss."
printf '\n'
if [[ -x "$ROOT/vendor/platform-tools/adb" ]]; then
  pause "Do the phone steps, then press Enter to verify"
  printf '\n'
  "$ROOT/vendor/platform-tools/adb" kill-server >/dev/null 2>&1 || true
  OUT="$("$ROOT/vendor/platform-tools/adb" devices -l 2>&1 | tail -n +2 | grep -v '^$' || true)"
  if [[ -n "$OUT" ]]; then
    printf '  %s✓ device visible%s\n' "$GREEN" "$RESET"
    printf '%s\n' "$OUT" | sed 's/^/    /'
    if printf '%s' "$OUT" | grep -q 'unauthorized'; then
      warn "State is 'unauthorized' — accept the prompt on the phone screen."
    fi
  else
    warn "Still nothing. Recheck: USB debugging on, USB mode = Transfer files,"
    warn "and for Huawei the 'allow ADB in charge-only mode' toggle."
  fi
else
  note "vendor/platform-tools/adb not found; skipping the live check."
fi
printf '\n'
pause "Press Enter to finish"
# ──────────────────────────────────────────────────────────────────────────

finish
note "Next: scripts/build.sh && scripts/notarize.sh"
note "      then scripts/verify-clean.sh on a fresh macOS 15 VM"
